### ISSUE TITLE
Warpinator is getting the ip from the wrong network

### ISSUE THREAD

**Issue by FurtadoPires** [slowscript/warpinator-windows#15]
I have two networks in my windows: the standard ethernet with static local ip, and the dhcp "VirtualBox Host-Only Network" which is used by virtualbox.

When I open Warpinator it always uses the ip from the virtualbox network instead of windows, so warpinator can't find any other device in the network.

Warpinator 0.2
Windows 11 22H2

**Comment by slowscript** [comment]
If you have multiple network interfaces, you can select which one to use in the settings. Don't forget to click the Restart button or restart the application manually.
![warpinator-settings-network](https://user-images.githubusercontent.com/40033124/196500387-f6318155-3f4d-4caf-9343-b5c49541629a.png)

**Comment by FurtadoPires** [comment]
I didn't saw that option before, thanks

But warpinator still can't see any other instances in the same network, do I have to manually set something in the windows firewall?

**Comment by slowscript** [comment]
Yes, the application needs to be allowed in the firewall at least on private networks (then you need to ensure that the network you are on is marked as private - and I never remember where that is set) but it is better to allow it on both public and private so that it won't suddenly stop working when you change the network. After changing firewall settings the application needs to be restarted.
