### ISSUE TITLE
Wine + MONO 6.12 = Fail.

### ISSUE THREAD

**Issue by juanpc2018** [slowscript/warpinator-windows#25]
Warpinator installer .exe
claims requires NET 4.0
github claims requires 4.6.2
latest mono 6.12 does Not work.

ive installed both 32 & 64 in Wine64drive

NET4.0 installer detects a better version, when mono 6.12 is installed.
and does Not allow to install over.

https://www.mono-project.com/download/stable/#download-win
32-Bit
PlayOnMac 4.4.3 https://www.playonmac.com/en/download.html
OSX Cata 10.15.7

There is No point running BigSur 11 or newer on intel CPU, runs emulated = slower.

When Wine 7.11 x32 is Configured for Win8.1
NET 4.6.2
requires:
KB2919355
https://support.microsoft.com/en-us/topic/windows-rt-8-1-windows-8-1-and-windows-server-2012-r2-update-april-2014-3c9d820b-7079-359d-8660-21de648fa31d
32
https://www.microsoft.com/en-us/download/details.aspx?id=42327
64
https://www.microsoft.com/en-us/download/details.aspx?id=42335
installed in the following order: 
clearcompressionflag.exe
KB2919355
KB2932046
KB2959977 
KB2937592 
KB2938439 
KB2934018

----

dot NET 4.8.0
https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0

-----

dot NET 4.5.1
https://www.microsoft.com/en-us/download/details.aspx?id=40779

-----

0024:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"Warpinator.exe" cannot be loaded
0024:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files (x86)\\Warpinator\\Warpinator.exe" failed, status c0000135
00b8:err:winediag:WS_getaddrinfo Failed to resolve your host name IP
00cc:fixme:rpc:handle_bind_error unexpected status value 1765
0050:err:rpc:RpcAssoc_BindConnection rejected bind for reason 0
00d4:fixme:rpc:handle_bind_error unexpected status value 1765
0084:err:rpc:RpcAssoc_BindConnection rejected bind for reason 0

https://learn.microsoft.com/en-us/answers/questions/909467/mscoree-dll-not-found-on-windows-11

-----

**Comment by slowscript** [comment]
The current release doesn't work because it requires some functions Wine doesn't implement yet. I've made a build with a couple of workarounds that you can try if you want: [warpinator-windows-dev.zip](https://github.com/slowscript/warpinator-windows/files/11131354/warpinator-windows-dev.zip). It runs and sends files on Linux with Wine 8.4 (staging) + Wine MONO (some version that Wine installs automatically). I can't test this on a mac. Only remaining limitation I've noticed is that it can't send folders.

**Comment by slowscript** [comment]
Now thinking about it, it would be probably better to try running the original Linux version on MacOS than to make this one work through Wine. The Linux verision is written in Python, so it should run everywhere without recompiling. Using GTK from Python on MacOS is [possible](https://stackoverflow.com/questions/49956985/how-to-install-pygtk-3-on-mac-os-x), the other dependencies should work too.

**Comment by slowscript** [comment]
The next release will contain a fix that allows running on Wine just like the development version in the zip file mentioned above. It will start on the condition that the `<System.Windows.Forms.ApplicationConfigurationSection>` section is removed from `Warpinator.exe.config` (Wine Mono does not support it).
There are still some other limitations (can't send folders, sets incorrect file modification time, does not detect change in network interfaces, crashes sometimes...) but these are due to missing features in Wine and it is not practical to work around them.
As for the specific error mentioned in this issue, it seems that .NET is not correctly installed. You don't need to install regular .NET or any of the KBxxx updates. Regular Mono that comes with Wine should be enough.
